<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Lp-ANKUSH26" failures="2" tests="2" name="Test(failed)" time="0.086" errors="0" timestamp="2025-05-16T16:24:33 IST">
  <testcase classname="testNG_Failed_TestCases.Class_A" name="testCase1" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG_Failed_TestCases.Class_A.testCase1(Class_A.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="testNG_Failed_TestCases.Class_B" name="testCase4" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNG_Failed_TestCases.Class_B.testCase4(Class_B.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase classname="testNG_Failed_TestCases.Class_A" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase classname="testNG_Failed_TestCases.Class_B" name="testCase3" time="0.0">
    <ignored/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- Test(failed) -->
